version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net 
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  spring-app:
    build: .
    ports:
      - "8080:5000"
    environment:
      DB_HOST: mysql-db:3306
      DB_NAME: db_test
      DB_USER: user
      DB_PASSWORD: pass
    depends_on:
      - mysql-db
    networks:
      - springapimysql-net  
            
networks:
  springapimysql-net: