name: Java Build and Beanstalk Update

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17  # Set Java version to 17
          distribution: adopt

      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v3
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version  # Verify AWS CLI installation

      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=us-east-1

      - name: Deploy new application new version on beanstalk
        run: |
          ls -l  
          ./deploy_application.sh

     
