name: Java Build, S3 Upload, and Beanstalk Update

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17  # Set Java version to 17

      - name: Build with Gradle
        run: ./gradleW build  # Run Gradle build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy application new version
        #run: aws s3 cp build/libs/*.jar s3://your-bucket-name/  # Update with your S3 bucket name
        run: ./deploy_application.sh

     
