name: Java Build and Beanstalk Update

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17  # Set Java version to 17
          distribution: adopt

      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v3
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version  # Verify AWS CLI installation

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1  # Update with your AWS region


      - name: Deploy new application new version on beanstalk
        #run: aws s3 cp build/libs/*.jar s3://your-bucket-name/  # Update with your S3 bucket name
        run: ./deploy_application.sh

     
